spring:
   profiles:
     active:
      -  dev

---

spring:
  profiles:  dev
  application:
    name:   microservicecloud-config-zpf-dev



---

spring:
  profiles:  test
  application:
    name:   microservicecloud-config-zpf-test
#必须保存为UTF-8格式

